#!/bin/bash

set -euo pipefail

ABSOLUTE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}/.")"

$ABSOLUTE_PATH/install-v13
$ABSOLUTE_PATH/install-v14
$ABSOLUTE_PATH/install-v13-classic
$ABSOLUTE_PATH/install-v14-classic
